/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE DATABASE IF NOT EXISTS `ht_carrental` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `ht_carrental`;

CREATE TABLE IF NOT EXISTS `tcar_audit_t` (
  `AUDIT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AUDIT_TYPE` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'table Name',
  `AUDIT_ACTIVE` char(1) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1.新增；2:修改；3:删除',
  PRIMARY KEY (`AUDIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='记录表';

/*!40000 ALTER TABLE `tcar_audit_t` DISABLE KEYS */;
/*!40000 ALTER TABLE `tcar_audit_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_car_models_t` (
  `CT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CT_LEVEL_ID` int(11) DEFAULT NULL COMMENT 'DICT_ID(DICT_TYPE=A)',
  `CT_NAME` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CT_IMG_URL` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '车模图片路径',
  `CT_DESC` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ESTIMATE_UNIT_PRICE` double(6,2) DEFAULT NULL,
  PRIMARY KEY (`CT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='车模表';

/*!40000 ALTER TABLE `tcar_car_models_t` DISABLE KEYS */;
INSERT INTO `tcar_car_models_t` (`CT_ID`, `CT_LEVEL_ID`, `CT_NAME`, `CT_IMG_URL`, `CT_DESC`, `ESTIMATE_UNIT_PRICE`) VALUES
	(1, 4, '别克君威2013', NULL, '自动|5人|三厢', 200.00);
/*!40000 ALTER TABLE `tcar_car_models_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_car_t` (
  `CAR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CT_ID` int(11) NOT NULL,
  `PLATE_NUMBER` varchar(7) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '车牌',
  PRIMARY KEY (`CAR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='汽车表';

/*!40000 ALTER TABLE `tcar_car_t` DISABLE KEYS */;
INSERT INTO `tcar_car_t` (`CAR_ID`, `CT_ID`, `PLATE_NUMBER`) VALUES
	(1, 1, '鄂A88888');
/*!40000 ALTER TABLE `tcar_car_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_dept_t` (
  `DEPT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPL_PHONE` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `DEPT_NAME` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `DEPT_ADDR` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`DEPT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='门店表';

/*!40000 ALTER TABLE `tcar_dept_t` DISABLE KEYS */;
INSERT INTO `tcar_dept_t` (`DEPT_ID`, `DEPL_PHONE`, `DEPT_NAME`, `DEPT_ADDR`) VALUES
	(1, '88888888', 'TEST-1', 'HBWHGG');
/*!40000 ALTER TABLE `tcar_dept_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_dictionary` (
  `DICT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `DICT_TYPE` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'A:级别；',
  PRIMARY KEY (`DICT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='字典表';

/*!40000 ALTER TABLE `tcar_dictionary` DISABLE KEYS */;
INSERT INTO `tcar_dictionary` (`DICT_ID`, `NAME`, `DICT_TYPE`) VALUES
	(1, '手动紧凑型', 'A'),
	(2, '经济型', 'A'),
	(3, '商务型', 'A'),
	(4, '豪华型', 'A'),
	(5, 'SUV', 'A'),
	(6, '6至15座商务', 'A'),
	(7, '个性车', 'A'),
	(8, '电动车', 'A');
/*!40000 ALTER TABLE `tcar_dictionary` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_employee_t` (
  `EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `DEPT_ID` int(11) NOT NULL,
  `ENABLE_FLAG` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Y:有效；N:无效',
  PRIMARY KEY (`EMPLOYEE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='员工表';

/*!40000 ALTER TABLE `tcar_employee_t` DISABLE KEYS */;
INSERT INTO `tcar_employee_t` (`EMPLOYEE_ID`, `USER_ID`, `DEPT_ID`, `ENABLE_FLAG`) VALUES
	(1, 1, 1, 'Y');
/*!40000 ALTER TABLE `tcar_employee_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_log_t` (
  `LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTIVE_TYPE` char(1) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '1.订单；2.门店；3.员工',
  `ACTIVE_USER` int(11) DEFAULT NULL COMMENT '操作员工',
  `ACTIVE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='日志表';

/*!40000 ALTER TABLE `tcar_log_t` DISABLE KEYS */;
/*!40000 ALTER TABLE `tcar_log_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_order_t` (
  `ORDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDER_NO` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `CREATE_USER_ID` int(11) NOT NULL COMMENT 'TCAR_USER_T.USER_ID',
  `CATEGORY_ID` int(11) NOT NULL,
  `GET_CAR_TYPE` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '1:自取；2:送达',
  `ESTI_START_DATE` date NOT NULL COMMENT '预估开始时间',
  `ESTI_END_DATE` date NOT NULL COMMENT '预估结束时间',
  `CT_ID` int(11) NOT NULL COMMENT '车型',
  `TOTLE_ESTI_AMT` double(6,2) DEFAULT NULL COMMENT '总预估金额',
  `DEPT_ID` int(11) DEFAULT NULL COMMENT '处理订单的门店，如果=0所有门店都可看到，默认=0',
  `ADDR` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '送车地址',
  `PROCESS_USER_ID` int(11) DEFAULT NULL COMMENT '订单处理人，由门店得到员工的用户ID',
  `ACTUAL_START_DATE` date DEFAULT NULL COMMENT '实际开始时间',
  `CAR_ID` int(11) DEFAULT NULL COMMENT '车牌',
  `ACTUAL_END_DATE` date DEFAULT NULL COMMENT '实际结束时间',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ORDER_STATUS` char(1) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'A:待取车;B:待还车;C:取消 F:完成;',
  `ATTR1` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '取车时照片目录',
  `ATTR2` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '还车时照片目录',
  PRIMARY KEY (`ORDER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='订单表';

/*!40000 ALTER TABLE `tcar_order_t` DISABLE KEYS */;
INSERT INTO `tcar_order_t` (`ORDER_ID`, `ORDER_NO`, `CREATE_USER_ID`, `CATEGORY_ID`, `GET_CAR_TYPE`, `ESTI_START_DATE`, `ESTI_END_DATE`, `CT_ID`, `TOTLE_ESTI_AMT`, `DEPT_ID`, `ADDR`, `PROCESS_USER_ID`, `ACTUAL_START_DATE`, `CAR_ID`, `ACTUAL_END_DATE`, `CREATE_TIME`, `UPDATE_TIME`, `ORDER_STATUS`, `ATTR1`, `ATTR2`) VALUES
	(1, '20170101025300001', 1, 0, '1', '2017-01-01', '2017-01-03', 1, 600.00, 1, NULL, NULL, NULL, NULL, NULL, '2017-01-02 03:09:08', '2017-01-02 02:54:38', 'A', NULL, NULL);
/*!40000 ALTER TABLE `tcar_order_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_role_t` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_TYPE` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT '1:微信；2:员工；3:管理员',
  `ROLE_NAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `RIGHT_CODE` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='角色表';

/*!40000 ALTER TABLE `tcar_role_t` DISABLE KEYS */;
INSERT INTO `tcar_role_t` (`ROLE_ID`, `ROLE_TYPE`, `ROLE_NAME`, `RIGHT_CODE`) VALUES
	(1, '1', 'wx', NULL),
	(2, '2', 'yg', NULL),
	(3, '3', 'admin', NULL);
/*!40000 ALTER TABLE `tcar_role_t` ENABLE KEYS */;

CREATE TABLE IF NOT EXISTS `tcar_user_t` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` int(11) NOT NULL COMMENT 'TCAR_ROLE_T外键',
  `USER_NAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT '用户名',
  `PASS_WORD` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT '密码',
  `USER_PHONE` varchar(12) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '手机号',
  `SHOW_NAME` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '显示名',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='用户表';

/*!40000 ALTER TABLE `tcar_user_t` DISABLE KEYS */;
INSERT INTO `tcar_user_t` (`USER_ID`, `ROLE_ID`, `USER_NAME`, `PASS_WORD`, `USER_PHONE`, `SHOW_NAME`) VALUES
	(1, 1, '18827648815', '1', '18827648815', 'lkh');
/*!40000 ALTER TABLE `tcar_user_t` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
